src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auth_Category__c</fullName>
        <label>Auth Category</label>
        <picklist>
            <picklistValues>
                <fullName>DME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Imaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Auth_Type__c</fullName>
        <label>Auth Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPT_Code__c</fullName>
        <label>CPT Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Diag_Code__c</fullName>
        <label>Primary Diag Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_From_Date__c</fullName>
        <label>Service From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Units__c</fullName>
        <label>Total Units</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Type_of_Case__c</fullName>
        <label>Type of Case</label>
        <picklist>
            <picklistValues>
                <fullName>UM</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Prior_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Approval__c</fullName>
        <label>Date of Approval</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_Auth_Desc__c</fullName>
        <label>Prior Auth Desc.</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Prior_Auth_Ref__c</fullName>
        <displayFormat>PC#{0000}</displayFormat>
        <label>Prior Auth Ref.</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Prior_Auth__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Prior Authorizations</relationshipLabel>
        <relationshipName>Prior_Authorizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prior Authorization</label>
    <nameField>
        <label>Prior Authorization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prior Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PagePreviewerControllerTest.cls
@isTest 
public class PagePreviewerControllerTest{

    static List<Account> testAcclist = new List<Account>();
    Id IDofthedocument;
    static Boolean showTif;
       
    static testMethod void pagepreviewTest(){
     Account testAccount =new Account(name='Test Account',Auth_Category__c='ME',Auth_Type__c ='Test Type',Service_From_Date__c =Date.Today(),
     Primary_Diag_Code__c ='test',CPT_Code__c='Test1',Total_Units__c='Two',DOB__c= Date.Today(),Start_Date__c= Date.Today(),End_Date__c=Date.Today());
     insert testAccount; 
     system.assertequals(testAccount.Name, 'Test Account');
        
    Case umCases = new Case(Description='Testing Purpose1',AccountId=testAccount.id,Type='email1',type_of_case__c='CM',Status='new',Priority='low',Subject='test1');
    insert umcases;  
    system.assertequals(umcases.Subject, 'test1');  
    PageReference pageRef = Page.PreviewPage;
    System.Test.setCurrentPage(pageRef);   
     
    apexpages.currentPage().getparameters().put('id',umcases.id);
    ApexPages.StandardController sc = new ApexPages.StandardController(umCases);
    PagePreviewerController pcntrl = new PagePreviewerController(sc);
    showTif=false; 
    
        
     Prior_Authorization__c testpa = new Prior_Authorization__c(name ='test prior',Prior_Auth__c =testAccount.id,Date_of_Approval__c =Date.Today(),Decision__c='Approved',Prior_Auth_Desc__c ='Ok'); 
     insert testpa;
      Prior_Authorization__c testpa1= [Select id,name,Prior_Auth__c,Date_of_Approval__c,Decision__c,Prior_Auth_Desc__c,Prior_Auth_Ref__c
      From Prior_Authorization__c where Prior_Auth__c =:testAccount.id];
      system.assertequals(testpa1.name, 'test prior');  
      
      pcntrl.loadTif();
        pcntrl.SaveValues();
          }

}