src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DND__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DND</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disease__c</fullName>
        <label>Disease</label>
        <picklist>
            <picklistValues>
                <fullName>Diabetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prone to Stress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicare Advantage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer patient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heart Patient</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>There are 4 levels of stratifications of Chronic conditions based on risk scoring</description>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>Level I</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Level II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level IV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <label>Physician</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CarePlusMembersOverviewctrl.cls
public class CarePlusMembersOverviewctrl{

 
    public string actId {get;set;}
    public Account acctLst {get;set;}
    
    public CarePlusMembersOverviewctrl(){
        actId = apexpages.currentpage().getparameters().get('Id');
        acctLst = [SELECT Age__c,DND__c,DOB__c,Level__c,Name,Physician__c,Gender__c,Type,Disease__c,Id FROM Account WHERE Id =: actId limit 1];
        System.debug('actId========>'+actId);
        
    }
    
}