src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Intervention__c</fullName>
        <label>Intervention</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Name__c</fullName>
        <label>Claim Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claims__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>CLA-101{000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Goal_Status__c</fullName>
        <label>Goal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intervention__c</fullName>
        <label>Intervention</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome_Status2__c</fullName>
        <formula>IF(ISPICKVAL(Outcome__c,&quot;On Track&quot;), IMAGE(&quot;/resource/1449817708000/right&quot;,&quot;right&quot;,25,25),(IF(ISPICKVAL(Outcome__c,&quot;Off Track&quot;),IMAGE(&quot;/resource/1449817685000/wrong&quot;,&quot;wrong&quot;,25,25),&quot;&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sleep__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sleep Data</relationshipLabel>
        <relationshipName>Sleep_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sleep Data</label>
    <nameField>
        <label>Record XID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sleep Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ViewMemberCtrlTest.cls
@isTest 
public class ViewMemberCtrlTest
{ 
    public String strDOB;
    public String strStartDate;
    public String strEndDate;
    public String Goal;
    public integer i;
    
     @isTest
    private static void testClass()
    {
    viewMemberCtrl controller = new viewMemberCtrl() ;
    }
  /*system.Test.StartTest(); 
     ApexPages.StandardController sc = new ApexPages.StandardController(testAccount);
     ViewMemberCtrl controller = new ViewMemberCtrl(sc);

     PageReference pageRef = Page.CarePlus_ViewMemberInfo_Dreamweaver; // Add your VF page Name here
     pageRef.getParameters().put('id', String.valueOf(testAccount.Id));
     Test.setCurrentPage(pageRef); 
     system.Test.StopTest();*/
         
  static testMethod void testAcctLst()
 {
     DateTime d = Date.Today() ;
     
     Account testAccount = new Account(Name='Test Account',DOB__c= Date.Today(),Start_Date__c= Date.Today(),End_Date__c=Date.Today());
       
     Account testAccount2 = new Account(Name='Test Account2',DOB__c= Date.Today(),Start_Date__c= Date.Today(),End_Date__c=Date.Today());
        
     List<Account> testAcclist = new List<Account>();
     testAcclist.add(testAccount);
     testAcclist.add(testAccount2);
     insert testAcclist;
    
     account testAccount1 =[SELECT Name FROM Account WHERE Id =:testAcclist[0].Id];
     system.assertequals(testAccount1.Name, 'Test Account');
   
     Goal__c testgoal = new Goal__c(Goal__c = testAcclist[0].Id, Name ='new member', Goal_Status__c='open');
     Goal__c testgoal1 = new Goal__c(Goal__c = testAcclist[0].Id, Name ='new member1',Goal_Status__c='open');   
     Goal__c testgoal2 = new Goal__c(Goal__c = testAcclist[0].Id, Name ='new member2', Goal_Status__c='closed');
     Goal__c testgoal3 = new Goal__c(Goal__c = testAcclist[0].Id, Name ='new member3',Goal_Status__c='closed');
     List<Goal__c> testgoallist = new List<Goal__c>();
     testgoallist.add(testgoal);
     testgoallist.add(testgoal1);
     testgoallist.add(testgoal2);
     testgoallist.add(testgoal3);   
     insert testgoallist;
        Goal__c testgoal5 = [SELECT Goal_Status__c,Goal__c,Id,Intervention__c,Name,Outcome_Status2__c
                             FROM Goal__c WHERE Id =:testgoallist[0].Id];
        system.assertNotEquals(testgoal5, NULL);    
         
     Claim__c testclaim = new Claim__c(Claims__c = testAccount.Id,Claim_Name__c='new');
     insert testclaim; 
     system.assertNotEquals(testclaim, NULL); 
     //testclaim = [SELECT Claim_Name__c FROM Claim__c WHERE Id =:testclaim.Id];
     
     Sleep__c tests = new Sleep__c(Account__c =testAccount.Id,Title__c = 'Test new');
     insert  tests;
     system.assertNotEquals(tests , NULL); 
     //tests = [SELECT Title__c FROM Sleep__c WHERE Id =:tests.Id];
     
     PageReference pageRef = Page.CarePlus_ViewMemberInfo_Dreamweaver;
      system.Test.setCurrentPage(pageRef);
     ApexPages.currentPage().getParameters().put('Id',testAccount.id);
     String id = ApexPages.currentPage().getParameters().get('id');
     system.assertEquals(true,id!=null);
     ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(testAccount);
     ViewMemberCtrl cntrl = new ViewMemberCtrl(sc);
     cntrl.getAcctLst();
     cntrl.getMemberGoal();
     cntrl.createGoal();
     cntrl.getContactBillingDetails();
     cntrl.dateFormat(testAcclist);
     
     
      

     
   
    
   

        // Case testcase = new Case(Account = testAccount.Id);
   //    insert testcase;
 }
}