src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DND__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DND</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disease__c</fullName>
        <label>Disease</label>
        <picklist>
            <picklistValues>
                <fullName>Diabetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prone to Stress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicare Advantage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer patient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heart Patient</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <label>Eligible</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Helath_Plan_Id__c</fullName>
        <label>Health Plan ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helath_Plan__c</fullName>
        <label>Health Plan</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <label>Physician</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>profilePic__c</fullName>
        <label>profilePic</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Intervention__c</fullName>
        <label>Intervention</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Name__c</fullName>
        <label>Claim Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim_Status__c</fullName>
        <label>Claim Status</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost_of_Claim__c</fullName>
        <label>Cost of Claim</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>CLA-101{000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sleep__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sleep Data</relationshipLabel>
        <relationshipName>Sleep_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Awakenings__c</fullName>
        <label>Awakenings</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Light_Sleep__c</fullName>
        <label>Light Sleep</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quality__c</fullName>
        <label>Quality</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sleep Data</label>
    <nameField>
        <label>Record XID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sleep Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ViewCaseMemberCtrl.cls
public with sharing class ViewCaseMemberCtrl {

    public ViewCaseMemberCtrl(ApexPages.StandardController controller) {
        
         caseId = apexpages.currentpage().getparameters().get('Id');
       }

          
    Id caseId {get;set;}
    public List<Case> caselist {get;set;}
    public List<Contact> cntLst {get;set;}
       
     public void getCasecntLst() {
     // cntLst = new List<Contact>([SELECT AccountId,MailingAddress,MailingCity,MailingCountry,MailingPostalCode,MailingState,MailingStreet,MobilePhone,Name,Email,Phone FROM Contact WHERE Id = :actId]);
        /*acctLst = [SELECT Age__c,DND__c,DOB__c,Name,Physician__c,Gender__c,Eligible__c,End_Date__c,Start_Date__c,Helath_Plan__c,Helath_Plan_Id__c,Type,Disease__c,Id,profilePic__c FROM Account WHERE Id =: actId];
        claimlist = [SELECT Claim_Name__c,Claim_Status__c,Cost_of_Claim__c FROM Claim__c WHERE Id =:caseId];
        caselist = [SELECT Intervention__c,Outcome__c,Reason,Status FROM Case WHERE Id =: caseId];
        sleeplist = [SELECT Account__c,Awakenings__c,Date__c,Light_Sleep__c,Name,Quality__c,Title__c FROM Sleep__c  WHERE Id =: actId];
        dateFormat(acctLst);*/
      }
    
    public ViewCaseMemberCtrl(){
        caseId= apexpages.currentpage().getparameters().get('Id');
        System.debug('caseId========>'+caseId);
       
    }
    

    public PageReference createGoal() {
        PageReference pf = new PageReference('/a0M/e?retURL=%2Fa0M%2Fo?core.apexpages.devmode.url=1');
        pf.getParameters().put('nooverride', '1');
        pf.setRedirect(true);
        
        return pf;
    }


       
    public void getContactBillingDetails(){
     
          cntLst = new List<Contact>([SELECT AccountId,MailingAddress,MailingCity,MailingCountry,MailingPostalCode,MailingState,MailingStreet,MobilePhone,Name,Email,Phone FROM Contact WHERE Id = :caseId ]);
    }
    
    
}