src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DND__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DND</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disease__c</fullName>
        <label>Disease</label>
        <picklist>
            <picklistValues>
                <fullName>Diabetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prone to Stress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicare Advantage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer patient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heart Patient</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Eligible__c</fullName>
        <label>Eligible</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Helath_Plan_Id__c</fullName>
        <label>Health Plan ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helath_Plan__c</fullName>
        <label>Health Plan</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <label>Physician</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/addDiseasePillsctrlTest.cls
@isTest
public  class addDiseasePillsctrlTest{  
 
    //public static  void testdata(){
   // addDiseasePillsctrl ctrl=new addDiseasePillsctrl();
    //}
    
  static testmethod void addAccountPilltest(){
  
   Account testAccount = new Account(Name='Test Account',DOB__c= Date.Today(),
                                  Age__c=34,DND__c=true,Physician__c='SSSSSSSSS',Gender__c='Male',Eligible__c='Yes',Helath_Plan__c='FlexiSuper',
                                  Helath_Plan_Id__c='ID0123453',Type='',Disease__c='Diabetic');
   Account testAccount1 = new Account(Name='Test Account1',DOB__c= Date.Today(),
                                  Age__c=32,DND__c=true,Physician__c='SSSSSSSSS',Gender__c='Male',Eligible__c='Yes',Helath_Plan__c='FlexiSuper',
                                  Helath_Plan_Id__c='ID40123453',Type='',Disease__c='Diabetic');
     List<Account> testacclst = new list<Account>();
       testacclst.add(testAccount);
        testacclst.add(testAccount1);
        insert  testacclst;
                                       
   testAccount = [SELECT Disease__c FROM Account WHERE Id =:testacclst[0].Id ];
    system.assertequals(testAccount.Name, 'Test Account');
     
      PageReference pageRef = Page.addDiseasePills;
      system.Test.setCurrentPage(pageRef);
     ApexPages.currentPage().getParameters().put('Id',testAccount.id);
     String id = ApexPages.currentPage().getParameters().get('id');
     system.debug('testacclst1============>'+testacclst[0].id);
     ApexPages.StandardController sc = new ApexPages.StandardController(testAccount);
       addDiseasePillsctrl cntrl = new addDiseasePillsctrl(sc);
      cntrl.savePill();
       }      
  }