src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disease__c</fullName>
        <label>Disease</label>
        <picklist>
            <picklistValues>
                <fullName>Diabetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prone to Stress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicare Advantage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer patient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heart Patient</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pillControllerTest.cls
@isTest 
public class pillControllerTest{


         static testMethod void addPillsTest(){
         
         Account mbr = new Account(Name='Test Account',Disease__C='Diabetic;Prone to Stress',DOB__c= Date.Today(),Start_Date__c= Date.Today(),End_Date__c=Date.Today());
         insert mbr;
         system.assertequals(mbr.Name, 'Test Account');
         
         ApexPages.standardController sc = new ApexPages.standardController(mbr);
         pillController pc = new pillController(sc);
         pc.selectedPill = 'Diabetic';
         pc.removePills();
         
         Account mbr1 = new Account(Name='Test Account1',DOB__c= Date.Today(),Start_Date__c= Date.Today(),End_Date__c=Date.Today());
         insert mbr1;
         system.assertequals(mbr1.Name, 'Test Account1');
         
         ApexPages.standardController sc1 = new ApexPages.standardController(mbr1);
         pillController pc1 = new pillController(sc1);
         
         }

                

}