src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>RAGStatus__c</fullName>
        <formula>IF (Time_Remaining__c &gt; 3,(IMAGE(&quot;https://c.cs41.visual.force.com/resource/1294667510000/Green&quot;,&quot;&quot;,25,25)),(IF (AND (Time_Remaining__c &gt; 0,Time_Remaining__c &lt;3),(IMAGE(&quot;https://c.cs41.visual.force.com/resource/1294667510000/Amber&quot;,&quot;&quot;,25,25)),(IF (Time_Remaining__c &lt; 0,(IMAGE(&quot;https://c.cs41.visual.force.com/resource/1294667510000/Red&quot;,&quot;&quot;,25,25)),&quot;&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Case__c</fullName>
        <label>Type of Case</label>
        <picklist>
            <picklistValues>
                <fullName>UM</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/imagingQueueCase_cntrlr.cls
public class imagingQueueCase_cntrlr {
    String queid='';

    public imagingQueueCase_cntrlr(ApexPages.StandardController controller) {

    }
    public List<Case> getCases() {        
        Id profileId=userinfo.getprofileid();
        String profName=[Select Id,Name from Profile where Id=:profileId].Name;
                
        if(profName =='UM_Nurse' || profName=='CM_UM_Nurse'){
            queid=[select Id from Group where Name = 'Nurse Inbox' and Type = 'Queue'].id;        
        }
        else{
        queid=[select Id from Group where Name = 'imaging queue' and Type = 'Queue'].id;
        }
        
        system.debug('%%%%%Queue Id is'+queid);
        String query= 'select Id,caseNumber,subject,ragstatus__c,type_of_case__c FROM Case where ownerid=:queid';
        
        
        if(profName=='UM_Nurse'){
            query+=' and Type_of_Case__c=\'UM\'';
        }
        else if(profName=='CM_UM_Nurse' || profName=='UM_Co-ordinator'){
            query+=' and (Type_of_Case__c=\'UM\' or Type_of_Case__c=\'CM\')';
        }
        else if(profName=='UM_Clerk'){
            query+=' and AccountId=null';
        }
        system.debug('%%%%%Query is'+query);
        return Database.query(query);
    }

}