src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>casestouserPO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RAGStatus__c</fullName>
        <formula>IF (Time_Remaining__c &gt; 3,(IMAGE(&quot;https://c.cs41.visual.force.com/resource/1294667510000/Green&quot;,&quot;&quot;,25,25)),(IF (AND (Time_Remaining__c &gt; 0,Time_Remaining__c &lt;3),(IMAGE(&quot;https://c.cs41.visual.force.com/resource/1294667510000/Amber&quot;,&quot;&quot;,25,25)),(IF (Time_Remaining__c &lt; 0,(IMAGE(&quot;https://c.cs41.visual.force.com/resource/1294667510000/Red&quot;,&quot;&quot;,25,25)),&quot;&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Remaining__c</fullName>
        <description>Time left for SLA to expire</description>
        <formula>(9-(Now() - CreatedDate))*24</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ProfilePic__c</fullName>
        <label>ProfilePic</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/HompageCtrl.cls
public with sharing class HompageCtrl{

    public String getMydetails() {
        return null;
    }


    public HompageCtrl() {

    }



        // Id actId {get;set;}
        Id userid{get;set;}
        public string currentusername{get;set;}
        public string currentprofilepic{get;set;}
        public string currentuserrole{get;set;}
        public string currentuserid {get;set;}
        public user  currentuser;
        public List<Case> caselist {get;set;}
        
        /*(private integer totalRecs = 0;
        private integer OffsetSize = 0;
        private integer LimitSize= 5;*/
       
        public HompageCtrl(ApexPages.StandardController controller) {
        caselist = new List<Case>();
        currentuser = new user();
        currentuser=[Select id,profilePic__c,FirstName,LastName,UserRole.Name from User where Id=:userinfo.getuserId()];
        currentuserid =currentuser.id;
        currentusername =(currentuser.FirstName+ ' '+ currentuser.LastName);
        currentprofilepic =currentuser.profilePic__c;
        currentuserrole=currentuser.UserRole.Name;
       // totalRecs = [SELECT count() FROM Case where Primary_Owner__c=:userinfo.getuserId()];
        //System.debug('Get case Details===============>'+totalRecs); 
            }
    
        public List<Case> getCaseDetails(){
    
        userid=UserInfo.getUserId();
        caselist =new List<case>([SELECT id,CaseNumber,subject,ragstatus__c,Time_Remaining__c,Primary_Owner__c FROM Case where Primary_Owner__c=:userid ORDER BY Time_Remaining__c DESC LIMIT 5]);
        //List<case> caselist = Database.Query('SELECT id,CaseNumber,subject,Time_Remaining__c,Primary_Owner__c FROM Case where Primary_Owner__c=:userid ORDER BY Time_Remaining__c DESC LIMIT :LimitSize OFFSET :OffsetSize');
        System.debug('Get case Details===============>'+caselist); 
        //caselist.setPageSize(5);
        return caselist;
        } 
        
           }