src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <label>Goal Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Status__c</fullName>
        <label>Goal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intervention__c</fullName>
        <label>Intervention</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome_Status2__c</fullName>
        <formula>IF(ISPICKVAL(Outcome__c,&quot;On Track&quot;), IMAGE(&quot;/resource/1449817708000/right&quot;,&quot;right&quot;,25,25),(IF(ISPICKVAL(Outcome__c,&quot;Off Track&quot;),IMAGE(&quot;/resource/1449817685000/wrong&quot;,&quot;wrong&quot;,25,25),&quot;&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GoalCtrl.cls
public class GoalCtrl {

    public PageReference createGoal() {
        PageReference pf = new PageReference('/a0M/e?retURL=%2Fa0M%2Fo?core.apexpages.devmode.url=1');
        pf.getParameters().put('nooverride', '1');
        pf.setRedirect(true);
        
        return pf;
    }


    public String Goal { get; set; }
    public List<Goal__c> goalLst {get;set;}
    public List<Goal__c> goalCloseLst {get;set;}
    public Integer i {get;set;}
    
    public void getMemberGoal() {
      
        goalLst = new List<Goal__c>([SELECT Goal_Name__c,Goal_Status__c,Goal__c,Id,Intervention__c,Name,Outcome_Status2__c FROM Goal__c WHERE Goal__c = '00155000005oKIdAAM' AND Goal_Status__c='Open']);
        goalCloseLst = new List<Goal__c>([SELECT Goal_Name__c,Goal_Status__c,Goal__c,Id,Intervention__c,Name,Outcome_Status2__c FROM Goal__c WHERE Goal__c = '00155000005oKIdAAM' AND Goal_Status__c='Closed']);
    }

}